### ISSUE TITLE
Обобщение арифметических операций

### ISSUE THREAD

**Issue by gltronred** [ArgumentExxxception/FP#5]
Кажется, что (как минимум) арифметические операции имеют очень много общего кода. Может, обобщить их?

https://github.com/ArgumentExxxception/FP/blob/5f961c71fa0e21768dd29cd82fa6ae301933a4c8/app/AritmeticOperations.hs#L13

**Comment by ArgumentExxxception** [comment]
Можно обобщить, думаю. Пока работаю с условными операторами и циклами, после поправлю
